### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by meghan06** [AzureADTrent/Asus-C425-Hackintosh#2]
1.) Why is your ROM messed up? GenSMBIOS should've generated a string to use.
2.) Remove SSDT-XOSI and its patch. Not needed.
3.) Make sure your VoodoolPS2 kext is the one I used, it's in my repo.
4.) Remove SSDT-PLUG, not needed for 12.3 and up.
5.) Add IntelBTPatcher.kext
6.) You're missing a required kext for USBToolBox, if you don't have it your map will not work [github repo here](https://github.com/USBToolBox/kext)

**Comment by AzureADTrent** [comment]
1.) GenSMBIOS generated string caused an issue with booting. Changing it to the one in the OpenCore documentation got it booting without issue. Corrected this in config.plist and will be testing this again.
2.) Removed from config.
3.) Corrected my statement as I got backlight and keymapping working. The VoodolPS2 kext is the one from your repo.
4.) Removed from config.
5.) That Kext is not for Monterey according to the Github page at the bottom. Bluetooth is working correctly. https://github.com/zxystd/IntelBTPatcher
6.) I mapped from a Windows bootable and it stated I did not need the other kext.

**Comment by meghan06** [comment]
"5.) That Kext is not for Monterey according to the Github page at the bottom. Bluetooth is working correctly. https://github.com/zxystd/IntelBTPatcher" 
That's included in the IntelWirelessFirmware package, why are you using that one? It's like a year outdated. The Bluetooth stack changed in macOS 12, requiring that kext. [the correct docs are here](https://openintelwireless.github.io/IntelBluetoothFirmware/FAQ.html#what-additional-steps-should-i-do-to-make-bluetooth-work-on-macos-monterey-and-newer)

6.)  Yes, you do need that kext. That is why USBToolbox has a "tool" and a "kext" in their GitHub repo.

**Comment by meghan06** [comment]
Do note that you don't need IntelBTPatcher for Bluetooth to work, but `bluetoothhd` **will**  crash, and sometimes even kernel panic.

**Comment by AzureADTrent** [comment]
Thanks, I have corrected both then.

**Comment by AzureADTrent** [comment]
I appreciate you assisting me in making this installation better and explaining where I went wrong. Thank you!
